package com.lambdaschool.usermodel.services;

import com.lambdaschool.usermodel.UserModelApplication;
import org.junit.After;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.mockito.MockitoAnnotations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import javax.persistence.EntityNotFoundException;

import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = UserModelApplication.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class UserServiceImplTest
{
    @Autowired
    UserService userService;

    @Autowired
    RoleService roleService;

    @Before
    public void setUp() throws Exception
    {
        MockitoAnnotations.initMocks(this);
    }

    @After
    public void tearDown() throws Exception
    {
    }

    @Test
    public void a_findUserById()
    {
        assertEquals("cinnamon",
            userService.findUserById(7)
                .getUsername());
    }

    @Test(expected = EntityNotFoundException.class)
    public void aa_findUserByIdFail()
    {
        assertEquals("barnbarn",
            userService.findUserById(777)
                .getUsername());
    }

    @Test
    public void b_findByNameContaining()
    {
        assertEquals(1,
            userService.findByNameContaining("cinna")
                .size());
    }

    @Test
    public void c_findAll()
    {
        assertEquals(5,
            userService.findAll()
                .size());
        // have 5 named users and 25 faker users generated by a commented out for loop
    }

    @Test
    public void d_delete()
    {
        userService.delete(7);
        assertEquals(4,
            userService.findAll()
                .size());
    }

    @Test(expected = EntityNotFoundException.class)
    public void da_deleteFail()
    {
        userService.delete(777);
        assertEquals(4,
            userService.findAll()
                .size());
    }

    @Test
    public void e_findByName()
    {
        assertEquals("admin",
            userService.findByName("admin")
                .getUsername());
    }

    @Test(expected = EntityNotFoundException.class)
    public void ea_findByNameFail()
    {
        assertEquals("test admin",
            userService.findByName("xXxadminxXx")
                .getUsername());
    }

    @Test
    public void f_save()
    {
    }

    @Test
    public void g_update()
    {
    }

    @Test
    public void h_deleteAll()
    {
    }
}